### ISSUE TITLE
[3.0] Crash when getting item from NEI in creative+ mode

### ISSUE THREAD

**Issue by rdp1408** [breakinblocks/nutsandbolts#69]
Crash 1: http://pastebin.com/ZhWZbw5v
Crash 2: http://pastebin.com/DignFZj8

Can be reproduced by placing a stirling engine, and while having a stirling engine in hand and a full inventory, searching "engine" in NEI, and right clicking on redstone engine to get one. This is in creative+ mode.

**Comment by Saereth** [comment]
This bug is reproducible for me and not just the stirling engine. It seems in this new version of NEI if your inventory is full it tries to put it in your armor slots and thats when it crashes.
http://pastebin.com/DRZYwjnL

Will check with the nei devs for a fix or roll us back to a previous version of NEi. I'll update this issue once I know more. For now just dont try to spawn in more items with a full inventory.

**Comment by Saereth** [comment]
This is a confirmed NEi bug for now, we wait for an update. simple enough to avoid

**Comment by Saereth** [comment]
This was fixed in the NEi updated
